# Generated by Django 5.2 on 2025-06-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default=None, max_length=100)),
                ('EmailAddress', models.EmailField(blank=True, max_length=254, null=True)),
                ('ContactNumber', models.IntegerField(blank=True, null=True)),
                ('YourMessage', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
