# Generated by Django 5.2 on 2025-06-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cate_name', models.CharField(max_length=20)),
                ('cate_image', models.ImageField(upload_to='category_images')),
                ('cate_status', models.BooleanField(default=True)),
                ('cateslug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
