# Generated by Django 5.1.1 on 2025-05-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='adress',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='demo',
            name='name',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
