# Generated by Django 5.1.1 on 2025-05-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_detail_delete_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
