# Generated by Django 5.1.1 on 2025-05-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demo',
            name='name',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
