# Generated by Django 5.1.1 on 2025-05-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_cont_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cont_us',
            old_name='contact',
            new_name='con',
        ),
    ]
