# Generated by Django 5.1.1 on 2025-05-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_rename_contact_cont_us_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cont_us',
            name='con',
            field=models.IntegerField(),
        ),
    ]
